Added customization for some Telescope menu keys
Dhanus3133/Leetbuddy.nvim pull request #31
Opened 2023-10-18 01:56 UTC by binarybrain11

User can now customize the keys set by LeetBuddy to navigate the Telescope menu. Alt keys are sometimes frustrating to use since many terminals and GUIs use Alt keys and don't send them to applications. This pull request allows users to easily specify alternate keybinds in the setup of LeetBuddy. Defaults remain the same, though I was unable to test any of them except for <CR> and <A-y> due to my setup.

2023-10-18 03:24 UTC, binarybrain11 commented
I've also added all of the example test cases instead of just the one sample test case.

2023-10-20 07:12 UTC, Dhanus3133 requested changes
Let the ctrl be the default key to filter the problems.

2023-10-20 07:12 UTC, Dhanus3133 commented on README.md
> +    }
```suggestion
    keys = {
        select = "<CR>",
        reset = "<C-r>",
        easy = "<C-e>",
        medium = "<C-d>",
        hard = "<C-h>",
        accepted = "<C-a>",
        not_started = "<C-y>",
        tried = "<C-t>",
    }
```

2023-10-20 07:12 UTC, Dhanus3133 commented on lua/leetbuddy/default_config.lua
> +  },
```suggestion
  keys = {
    select = "<CR>",
    reset = "<C-r>",
    easy = "<C-e>",
    medium = "<C-m>",
    hard = "<C-h>",
    accepted = "<C-a>",
    not_started = "<C-y>",
    tried = "<C-t>",
  },
```

2023-10-20 08:55 UTC, Dhanus3133 approved these changes

2023-10-20 08:57 UTC, merged

2023-10-20 08:58 UTC, Dhanus3133 commented
Merged! Thanks for the PR. :+1: